### PR TITLE
pollingDB example

### PR DESCRIPTION
**Pull request by anthrogan**
simple example of polling a DB to demonstrate normal use practice (Also avoids using setTimout with a async function)

### CODE REVIEW

**Comment by psi-4ward** [comment]
Hi,
pls move the file to `examples/db-poll.js`.

`setInterval` is actually okay but if you poll many areas in short time it could lead to overload so pls

* wait for `connect` event
* use `setTimeout` to schedule the next poll after the first was has finished

**Comment by anthrogan** [comment]
Changes made 👍 

I'll adopt the setTimeout method in my local app also it seems nicer doing it this way, plus it has a better way to deal with errors

**Comment by psi-4ward** [comment]
cool, did you test it?
whats the behavior if you kill the s7 server and break the connection?

**Comment by anthrogan** [comment]
I tested connecting and polling at first.

disconnecting isnt so great.
it actually hangs when the **client** looses connection. It doesn't ever timout from what I can see and it won't reconnect either. This is for an actual PLC (I cannot unplug its network at the minute)

starting the app without a good connection will work as expected with autoConnect but once connection is made and removed it hangs. When disconnect is called it works OK...

I will make a PLCSIM and try it that way maybe tomorrow, I like to run this stuff on actual PLC's though as its closer to real world :)

```

// function to start polling DB valus
let pollTimeout;
let time = new Date().toISOString();
async function pollDB() {
  try {
    const plcResult = await client.readDB(dbNr, dbVars);
    console.log(time, plcResult);
  } catch (err) {
    console.error('Error readDB:', err, 'retry in 10s');
  }
  pollTimeout = setTimeout(pollDB, 10 * 1000);
}

// function to stop polling
function stopPollDB() {
  clearTimeout(pollTimeout);
}

// Setup S7Client
let client = new S7Client(plcSettings);
client.on('connect', () => console.log('Connected to PLC'));
client.on('connect', pollDB);
client.on('disconnect', () => console.log('Disconnected from PLC'));
client.on('disconnect', stopPollDB);
client.on('connect_error', () => console.log('Connection Error to PLC'));
client.on('connect_error', stopPollDB);
client.on('error', err => console.error('PLC Error', err));
client.on('error', stopPollDB);


// Connect
(async function () {
  try {
    // auto reconnect
    await client.autoConnect();
  } catch (e) {
    console.error(e);
  }
})();
```

**Comment by anthrogan** [comment]
Disconnect seems OK, however client loosing connection is a bit of a issue. I get the same problem with a Omron library also, if for example you disable a NIC on the client PC it will do nothing. I guess its safe as the client can't communicate to the CP in a broken state but I'm not sure.

**Comment by mathiask88** [comment]
The underlying snap7 library uses sockets and it is not possible to determine the connection state until you try to read or write to the socket. So if you disconnect your cable or disable the NIC it won't recognize it until your next function call. So the `Connected` property has to be treated with some caution.

**Comment by psi-4ward** [comment]
thx @mathiask88 
I've implemented an alive check using `getCpuInfo` to have some kind of keep alive.

https://github.com/psi-4ward/s7client/blob/master/src/index.js#L72

**Comment by anthrogan** [comment]
thanks @mathiask88 

in that case @psi-4ward I'll add a getCpuInfo as an alive check? It will at least show an error and stop attempting to poll the DB as it will emit error

```


// function to start polling DB valus
let pollTimeout;
let time = new Date().toISOString();
async function pollDB() {
  try {
    const alive = await atg.getCpuInfo();
    const plcResult = await client.readDB(dbNr, dbVars);
    console.log(time, plcResult);
  } catch (err) {
    console.error('Error readDB:', err, 'retry in 10s');
  }
  pollTimeout = setTimeout(pollDB, 10 * 1000);
}

// function to stop polling
function stopPollDB() {
  clearTimeout(pollTimeout);
}

// Setup S7Client
let client = new S7Client(plcSettings);
client.on('connect', () => console.log('Connected to PLC'));
client.on('connect', pollDB);
client.on('disconnect', () => console.log('Disconnected from PLC'));
client.on('disconnect', stopPollDB);
client.on('connect_error', () => console.log('Connection Error to PLC'));
client.on('connect_error', stopPollDB);
client.on('error', err => console.error('PLC Error', err));
client.on('error', stopPollDB);



```

**Comment by psi-4ward** [comment]
You can remove `const alive = await atg.getCpuInfo();` again. cause `connect()` setup the check.

**Comment by storm-k** [comment]
Hi @psi-4ward  ,your program work well.

if i have 2 plcs , should i make 2 program (change ip), then "node 1.js" "node 2.js"  ? thanks

**Comment by psi-4ward** [comment]
> if i have 2 plcs , should i make 2 program (change ip), then "node 1.js" "node 2.js" ? thanks

depends on your needs. should work both, separate node processes or one handling two connections

**Pull request merged**
